version: 2
jobs:
  build:
    working_directory: ~/elixir_mock
    docker:
      - image: circleci/elixir:1.4
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test