version: 2
jobs:
  build:
    working_directory: ~/elixir_mock
    docker:
      - image: circleci/elixir:1.4
    steps:
      - checkout
      - run: mix deps.get
      - run: mix test

#  publish:
#    working_directory: ~/elixir_mock
#    docker:
#        - image: trenpixster/elixir:1.4.4
#    steps:
#      - run: mix docs